version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-db:/data/db
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
  content:
    build: ./content
    ports:
      - "8002:8002"
  user:
    build: ./user
    ports:
      - "8001:8001"

volumes:
    data-db: